<a href="https://colab.research.google.com/github/bilalzardoa/machine-learning/blob/main/mnist_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np
import keras

## analysis

In [53]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [54]:
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [55]:
x_train[0][:6] , y_train[0]

(array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
           0

In [56]:
def normalize(x):
  return x / 255

In [57]:
print(x_train.shape)
print(f"60 000 instances and each one should have shape {x_train[0].flatten().shape} to pass to dense layer")

(60000, 28, 28)
60 000 instances and each one should have shape (784,) to pass to dense layer


In [58]:
x_train = x_train.reshape(60000,28*28).T
x_test = x_test.reshape(10000,28*28).T

In [59]:
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((784, 60000), (60000,), (784, 10000), (10000,))

In [60]:
# simple architecture with an input and output layer
w1 = np.random.randn(784,32)
w2 = np.random.randn(32,10)

b1 = np.zeros(shape=(32,1))
b2 = np.zeros(shape=(10,1))

In [61]:
w1.T.shape ,x_train.shape , b1.shape

((32, 784), (784, 60000), (32, 1))

In [62]:
def relu(x):
  return np.maximum(0,x)

def softmax(Z):
    e_Z = np.exp(Z - np.max(Z, axis=0, keepdims=True))
    return e_Z / np.sum(e_Z, axis=0, keepdims=True)

def evaluate(a,b):
  pass

In [63]:
def forward_propagation(weights,biases,inputs):
  assert len(weights) == len(biases)

  A_list = []
  Z_list = []

  output_idx = len(weights) - 1

  n = len(weights)
  for i in range(n):
    Z = np.dot(weights[i].T,inputs) + biases[i]
    if i == output_idx:
      A = softmax(Z)
    else : A = relu(Z)

    A_list.append(A)
    Z_list.append(Z)

    inputs = A

  return Z_list,A_list

In [64]:
# TEST
Z_list , A_list = forward_propagation(weights=[w1,w2],biases=[b1,b2],inputs=x_train)
pred_probs = A_list[-1]
pred_labels = np.argmax(pred_probs,axis=0)
print(pred_probs.shape)

(10, 60000)


In [65]:
len(A_list) , len(Z_list)

(2, 2)

In [66]:
def one_hot(Y, num_classes):
    return np.eye(num_classes)[Y].T   # shape (num_classes, m)


In [67]:
A_list[-1].shape , one_hot(y_train,10).shape

((10, 60000), (10, 60000))

In [68]:
A_list[-1] , one_hot(y_train,10)

(array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         4.26374406e-116, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [1.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         1.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 1.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000]]),
 array([[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., 

## neural network

Cross-Entropy Loss (Multi-class)

$$
L = - \frac{1}{m} \sum_{i=1}^{m} \sum_{k=1}^{K} Y_{k,i} \log(A^{[L]}_{k,i})
$$

In [69]:
import numpy as np

class nn:
    class Optimizers:
        def __init__(self):
            pass

        def gradient_descent(self, weights, biases, dW, dB, learning_rate=0.01):
            for i in range(len(weights)):
                weights[i] -= learning_rate * dW[i]
                biases[i]  -= learning_rate * dB[i]
            return weights, biases

    class activations:
      @staticmethod
      def relu(x):
          return np.maximum(0, x)

      @staticmethod
      def relu_derivative(x):
          return (x > 0).astype(float)

      @staticmethod
      def softmax(Z):
          e_Z = np.exp(Z - np.max(Z, axis=0, keepdims=True))
          return e_Z / np.sum(e_Z, axis=0, keepdims=True)


    def __init__(self, layer_sizes):
        """
        layer_sizes: list defining sizes of each layer
                    e.g. [input_dim, hidden1, hidden2, output_dim]
        """
        self.Optimizers = nn.Optimizers()

        # He Normal initialization for ReLU activations
        self.weights = [
            np.random.randn(layer_sizes[i], layer_sizes[i+1]) * np.sqrt(2.0 / layer_sizes[i])
            for i in range(len(layer_sizes)-1)
        ]
        self.biases = [np.zeros((layer_sizes[i+1], 1)) for i in range(len(layer_sizes)-1)]


    def forward_propagation(self, weights, biases, inputs):
        A_list = [inputs]
        Z_list = []

        output_idx = len(weights) - 1

        for i in range(len(weights)):
            Z = np.dot(weights[i].T, A_list[-1]) + biases[i]
            if i == output_idx:
                A = nn.activations.softmax(Z)
            else:
                A = nn.activations.relu(Z)

            Z_list.append(Z)
            A_list.append(A)

        return Z_list, A_list

    def backwards_propagation(self, Z_list, A_list, weights, biases, y):
        m = y.shape[0]  # number of samples
        y_onehot = np.eye(A_list[-1].shape[0])[y].T  # one-hot labels

        dW = [0] * len(weights)
        dB = [0] * len(biases)

        dZ = A_list[-1] - y_onehot  # output layer derivative

        for i in reversed(range(len(weights))):
            A_prev = A_list[i]
            dW[i] = (1/m) * np.dot(A_prev, dZ.T)
            dB[i] = (1/m) * np.sum(dZ, axis=1, keepdims=True)

            if i > 0:  # backprop into hidden layers
                dA_prev = np.dot(weights[i], dZ)
                dZ = dA_prev * nn.activations.relu_derivative(Z_list[i-1])

        return dW, dB

    def compute_loss(self, y_pred, y_true):
        m = y_true.shape[0]
        y_onehot = np.eye(y_pred.shape[0])[y_true].T
        loss = -np.sum(y_onehot * np.log(y_pred + 1e-8)) / m
        return loss

    def fit(self, X, y, epochs=100, learning_rate=0.01, verbose=True):
        losses = []
        for epoch in range(epochs):
            # Forward
            Z_list, A_list = self.forward_propagation(self.weights, self.biases, X)

            # Compute loss
            loss = self.compute_loss(A_list[-1], y)
            losses.append(loss)

            # Backward
            dW, dB = self.backwards_propagation(Z_list, A_list, self.weights, self.biases, y)

            # Update
            self.weights, self.biases = self.Optimizers.gradient_descent(
                self.weights, self.biases, dW, dB, learning_rate
            )

            if verbose and (epoch % max(1, epochs//10) == 0 or epoch == epochs-1):
                print(f"Epoch {epoch+1}/{epochs} - Loss: {loss:.4f}")

        return losses

    def predict(self, X):
        _, A_list = self.forward_propagation(self.weights, self.biases, X)
        return np.argmax(A_list[-1], axis=0)


In [71]:
# Define model: 784 -> 128 -> 64 -> 10
model = nn([784, 32, 64,128, 10])
# Train (this might take time without GPU)
losses = model.fit(normalize(x_train), y_train, epochs=100, learning_rate=0.1)

# Predictions
y_pred = model.predict(normalize(x_test))
# Accuracy
acc = np.mean(y_pred == y_test)
print("Test Accuracy:", acc)


Epoch 1/100 - Loss: 2.6238
Epoch 11/100 - Loss: 2.0089
Epoch 21/100 - Loss: 1.2826
Epoch 31/100 - Loss: 0.8408
Epoch 41/100 - Loss: 0.8742
Epoch 51/100 - Loss: 0.6590
Epoch 61/100 - Loss: 0.5793
Epoch 71/100 - Loss: 0.5060
Epoch 81/100 - Loss: 0.4866
Epoch 91/100 - Loss: 0.4347
Epoch 100/100 - Loss: 0.3910
Test Accuracy: 0.8948
